# 100 excercises in Numpy
- got the idea from this github: https://github.com/rougier/numpy-100

In [1]:
import numpy as np

#### 1. Create a numpy array

In [2]:
a = np.arange(15).reshape(3, 5)

In [3]:
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


#### 2. Find the shape of an numpy array

In [4]:
a.shape

(3, 5)

#### 3. Find the dimension and data type of a numpy array

In [5]:
a.ndim

2

In [6]:
a.dtype.name

'int64'

#### 4. How to find the memory size of any array

In [7]:
a.size

15

# Printing arrays
#### When you print an array, NumPy displays it in a similar way to nested lists, but with the following layout:

- the last axis is printed from left to right,

- the second-to-last is printed from top to bottom,

- the rest are also printed from top to bottom, with each slice separated from the next by an empty line.
- If an array is too large to be printed, NumPy automatically skips the central part of the array and only prints the corners:

#### One-dimensional arrays are then printed as rows, bidimensionals as matrices and tridimensionals as lists of matrices.

In [8]:
print(np.arange(5)) # 1d array

[0 1 2 3 4]


In [9]:
print(np.arange(6).reshape(2, 3)) # 2d array

[[0 1 2]
 [3 4 5]]


In [10]:
print(np.arange(24).reshape(3, 2, 4)) # 3d array

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]]


In [11]:
np.atleast_2d([2, 3, 4]).shape

(1, 3)

In [12]:
np.core # where np is located

<module 'numpy.core' from 'c:\\Users\\thotc\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\numpy\\core\\__init__.py'>

#### 5. Get documentation on a function

In [13]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

#### 6. Create a null vector of size 10 but the fifth value which is 1

In [14]:
a = np.zeros(10)
a[4] = 1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49

In [15]:
a = np.arange(10, 50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last)

In [16]:
a = np.arange(10)
print(a)
print(a[::-1])

[0 1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]


In [17]:
np.flip(a)

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8

In [18]:
print(np.arange(9).reshape((3, 3)))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0]

In [19]:
np.nonzero(np.array([1, 2, 0, 0, 4, 0]))
# np.where(np.array([1, 2, 0, 0, 4, 0] != 0))

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix

In [20]:
A = np.diag(np.ones(3))
A

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values

In [23]:
np.random.random(27).reshape((3, 3, 3))

array([[[0.30629397, 0.04115016, 0.48436634],
        [0.62808987, 0.33168973, 0.90754543],
        [0.29673747, 0.40167219, 0.89479463]],

       [[0.64252288, 0.17331899, 0.10317411],
        [0.93290711, 0.81096579, 0.21903909],
        [0.5768649 , 0.52117699, 0.134196  ]],

       [[0.44832741, 0.18492914, 0.09670066],
        [0.8279314 , 0.39338692, 0.63997202],
        [0.80370948, 0.82338189, 0.9491625 ]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [24]:
a = np.random.random(100).reshape((10, 10))
print(a.min())
print(a.max())

0.003306466390050611
0.9995181663035573


#### 14. Create a random vector of size 30 and find the mean value

In [25]:
a = np.random.random(30)
a.mean()

np.float64(0.5066694476672904)

#### 15. Create a 2d array with 1 on the border and 0 inside

In [ ]:
a = np.zeros((10, 10))
a[:, [0, -1]] = 1 # select 2 columns, first and last
a[[0, -1], ] = 1 # select 2 rows, first and last
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array?

In [31]:
# make the array with ones first
ones = np.ones((5, 5))
# set the zeros 1 size smaller than the arrays
ones = np.pad(ones, pad_width=1, mode="constant", constant_values=0)
print(ones)


[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression?
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [32]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [33]:
M = np.zeros((5, 5))
a = np.arange(1, 5)
M[a, a- 1] = a
M

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [34]:
matrix = np.zeros((8, 8))
matrix[1::2, ::2] = 1
matrix[::2, 1::2] = 1
matrix


array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [36]:
np.unravel_index(99, (6, 7, 8))

(np.int64(1), np.int64(5), np.int64(3))

#### 21. Create a checkerboard 8x8 matrix using the tile function

In [37]:
a = np.array([[0, 1], [1, 0]])
np.tile(a, (4, 4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix

In [38]:
M = np.random.random((5, 5))
(M - M.mean()) / M.std() # Z-score normalization, There are other methods beside this

array([[-1.0174559 ,  0.46349012, -0.68886666, -0.51322871,  1.19509241],
       [ 1.53548165, -1.12319627,  1.60200158, -0.97273001,  1.3195335 ],
       [-0.63309833,  0.36319632,  0.44867818, -0.90789889,  1.3275361 ],
       [-1.72695051, -0.17332824,  0.62320662, -1.52483667,  0.61418996],
       [-0.18370339, -0.0369887 ,  1.44764551, -0.47137538, -0.9663943 ]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA)

In [39]:
RGBA = np.dtype([
    ('r', np.uint8),
    ('g', np.uint8),
    ('b', np.uint8),
    ('a', np.uint8)
])

print(RGBA)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

In [40]:
np.random.seed(42)
A = np.random.randint(0, 10, size=(5, 3)) 
B = np.random.randint(0, 10, size=(3,2))
print(A)
print(B)
print(A @ B) 

[[6 3 7]
 [4 6 9]
 [2 6 7]
 [4 3 7]
 [7 2 5]]
[[4 1]
 [7 5]
 [1 4]]
[[52 49]
 [67 70]
 [57 60]
 [44 47]
 [47 37]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place.

In [41]:
a = np.arange(10)

a[ (a > 3) & (a < 8)] *= -1
a

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9])

#### 26. What is the output of the following script?
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [42]:
# trick question, first one is the regular sum, add from 0-5, then add -1
# 2nd question, add from 0-5, with axis -1, which means the only axis or the last axis
# print(sum(range(5),-1)) # 
# from numpy import *
# print(sum(range(5),-1))
# should be 9 and 10

#### 27. Consider an integer vector Z, which of these expressions are legal?
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [43]:
Z = np.array([1, 2,3])
Z**Z,
2 << Z >> 2
1j*Z
Z/1/1
# Z<Z>Z # not legal, can't do bitwise left and right shift with vector

array([1., 2., 3.])

#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [44]:
# error np.array(0) / np.array(0)
# error np.array(0) // np.array(0)
# error np.array([np.nan]).astype(int).astype(float)


#### 29. How to round away from zero a float array ?

In [45]:
np.random.seed(42)
Z = np.random.uniform(-10, 10, 10)
np.copysign(np.ceil(np.abs(Z)), Z)

array([-3., 10.,  5.,  2., -7., -7., -9.,  8.,  3.,  5.])

#### 30. How to find common values between two arrays?

In [46]:
np.intersect1d(np.array([1, 2, 3]), np.array([10, 3, 4]))

array([3])

#### 31. How to ignore all numpy warnings (not recommended)?

In [47]:
# np.seterr(all='ignore')

#### 32. Is the following expressions true?
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [48]:
# np.sqrt(-1) == np.emath.sqrt(-1), No

#### 33. How to get the dates of yesterday, today and tomorrow?

In [49]:
today = np.datetime64('today', 'D')
yesterday = today - np.timedelta64(1, 'D')
tommorrow = today + np.timedelta64(1, 'D')
print(f"today: {today}")
print(f"yesterday: {yesterday}")
print(f"tommorrow: {tommorrow}")

today: 2025-10-15
yesterday: 2025-10-14
tommorrow: 2025-10-16


#### 34. How to get all the dates corresponding to the month of July 2016?

In [50]:
np.arange(np.datetime64("2016-07-01"), np.datetime64("2016-08-01"), dtype="datetime64[D]")

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? 

In [51]:
A = np.arange(5, dtype='float64')
B = np.arange(5, dtype='float64')
np.multiply(np.add(A, B, out=B), np.negative(np.divide(A, 2, out=A)), out=A)

array([ -0.,  -1.,  -4.,  -9., -16.])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods

In [52]:
np.random.seed(42)
a = np.random.random(5) * 5
print(np.floor_divide(a,  1)) # floor divide
print(np.floor(a)) # rounding, floor and celing
print(np.astype(a, np.int64)) # convert from float to int
print(np.trunc(a)) # actually truncate the values


[1. 4. 3. 2. 0.]
[1. 4. 3. 2. 0.]
[1 4 3 2 0]
[1. 4. 3. 2. 0.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4

In [53]:
np.tile(np.arange(5), 5).reshape((5, 5)) # my way

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [54]:
np.tile(np.arange(5), (5, 1))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [55]:
# create all zeros matrix, then all each row from 0-4
Z = np.zeros((5,5), dtype='int64') # include the dtype, otherwise np will give float
Z += np.arange(5)
Z

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array

In [56]:
np.fromiter((x for x in range(10)), dtype=np.int64)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded

In [57]:
np.linspace(0, 1, 11,endpoint=False)[1:] # need to use endpoint as false, then take out the initial value.
# there are so many ways to achieve this without this weird answer

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it

In [58]:
np.sort(np.random.random(10))

array([0.02058449, 0.05808361, 0.15599452, 0.18182497, 0.21233911,
       0.60111501, 0.70807258, 0.83244264, 0.86617615, 0.96990985])

#### 41. How to sum a small array faster than np.sum?

In [59]:
# instead of using np.sum, use np.add.reduce
a = np.arange(1, 10)
np.add.reduce(a)

np.int64(45)

#### 42. Consider two random arrays A and B, check if they are equal

In [60]:
np.array_equal([1, 2], [1, 2]) #
# use np.allclose if they are floats

True

#### 43. Make an array immutable (read-only)

In [61]:
a = np.arange(1, 6)
a.flags.writeable = False # need to set this flag to false
a[3] = 10 # 

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates

In [62]:
a = np.random.random(20).reshape((10, 2))
# need to use the r = sqrt(x^2 + y^2), theta = arctan(y/x)
def cart2pol(coord):
    x, y = coord
    rho = np.hypot(x, y)
    phi = np.arctan2(y, x)
    return rho, phi
print(a)

b = np.apply_along_axis(cart2pol, 1, a)
print(b)

[[0.18340451 0.30424224]
 [0.52475643 0.43194502]
 [0.29122914 0.61185289]
 [0.13949386 0.29214465]
 [0.36636184 0.45606998]
 [0.78517596 0.19967378]
 [0.51423444 0.59241457]
 [0.04645041 0.60754485]
 [0.17052412 0.06505159]
 [0.94888554 0.96563203]]
[[0.35524718 1.02830298]
 [0.67966596 0.68868891]
 [0.67762702 1.1265495 ]
 [0.32373914 1.12532471]
 [0.58499644 0.89404533]
 [0.81016721 0.24902584]
 [0.7844693  0.85592681]
 [0.60931797 1.49448884]
 [0.18251078 0.36443989]
 [1.35382015 0.79414505]]


#### 45. Create random vector of size 10 and replace the maximum value by 0

In [63]:
a = np.ones(10)
a[7] = 10
a[a.argmax()] = 0 # argmax returns the index
a.max() # max returns the value


np.float64(1.0)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area

In [64]:
A = np.zeros((10, 10), [('x', float), ('y', float)])
print(A)
x = np.linspace(0, 1, 10)
y = np.linspace(0, 1, 10)
A['x'], A['y'] = np.meshgrid(x, y)
print(A)

[[(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)
  (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)
  (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)
  (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)
  (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)
  (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)
  (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)
  (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)
  (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)
  (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)
  (0., 0.) (0., 0.)]]
[[(0.        , 0.        ) (0.11111111, 0.       

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [65]:
np.random.seed(42)
x = np.random.random(5) * np.arange(1, 6)
y = np.random.random(5) * np.arange(1, 6)
print(x)
print(y)
cauchy = 1.0 / (x.reshape((-1, 1)) - y) # the reshape (-1, 1) turns it into a column
print(cauchy)

[0.37454012 1.90142861 2.19598183 2.39463394 0.7800932 ]
[0.15599452 0.11616722 2.59852844 2.40446005 3.54036289]
[[   4.57570414    3.87037503   -0.44964265   -0.49263027   -0.31587365]
 [   0.57292338    0.56014206   -1.43451478   -1.98794734   -0.61015259]
 [   0.49019913    0.48081209   -2.48418437   -4.7966641    -0.74383672]
 [   0.4466999     0.43889164   -4.90449717 -101.76967093   -0.87280678]
 [   1.60231071    1.50619201   -0.54992335   -0.61562448   -0.36228344]]


In [66]:
x_reshape = x.reshape((-1, 1))
x.shape

(5,)

#### 48. Print the minimum and maximum representable values for each numpy scalar type

In [67]:
np.iinfo(np.int64) # use the iinfo function

iinfo(min=-9223372036854775808, max=9223372036854775807, dtype=int64)

#### 49. How to print all the values of an array?

In [68]:
# question is meant to ask, how to display all the values of an array if the array is very large.
# need to use set_printoptions
# https://numpy.org/doc/stable/user/quickstart.html#tricks-and-tips
import sys
np.set_printoptions(threshold=sys.maxsize)
print(np.arange(10000)) # not really sure what the questions here is

[   0    1    2    3    4    5    6    7    8    9   10   11   12   13
   14   15   16   17   18   19   20   21   22   23   24   25   26   27
   28   29   30   31   32   33   34   35   36   37   38   39   40   41
   42   43   44   45   46   47   48   49   50   51   52   53   54   55
   56   57   58   59   60   61   62   63   64   65   66   67   68   69
   70   71   72   73   74   75   76   77   78   79   80   81   82   83
   84   85   86   87   88   89   90   91   92   93   94   95   96   97
   98   99  100  101  102  103  104  105  106  107  108  109  110  111
  112  113  114  115  116  117  118  119  120  121  122  123  124  125
  126  127  128  129  130  131  132  133  134  135  136  137  138  139
  140  141  142  143  144  145  146  147  148  149  150  151  152  153
  154  155  156  157  158  159  160  161  162  163  164  165  166  167
  168  169  170  171  172  173  174  175  176  177  178  179  180  181
  182  183  184  185  186  187  188  189  190  191  192  193  194  195
  196 

#### 50. How to find the closest value (to a given scalar) in a vector?

In [69]:
arr = np.arange(0, 20)
scalar = 7
# find the differences between scalar and vector
# get the absolute value
# get the index with argmin, then use it to get the value from the array
arr[np.argmin(np.abs(arr - scalar))]

np.int64(7)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b)

In [70]:
# Use tuples
position = np.dtype([("x", float), ("y", float)])
color = np.dtype([("r", float), ("g", float), ("b", float)])
a = np.zeros(33, [("position",  position), ("color",  color)])
a


array([((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.))],
      dtype=[('positio

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances 

In [71]:
points = np.random.random((100,2))

diff = points[:, None, :] - points[None, :, :]

np.linalg.norm(diff, axis=-1) # another option is to use scipy.spatial.distance.cdist

array([[0.        , 1.11041752, 0.80286309, 0.52784779, 0.79361514,
        1.01940622, 0.6618271 , 0.4730478 , 0.489605  , 1.08617078,
        0.99173585, 0.04918683, 0.95874978, 0.91731745, 0.84915972,
        0.4854526 , 0.06214204, 0.38887557, 0.53582867, 0.94505043,
        0.9687824 , 0.92197676, 0.57931044, 0.77690056, 0.64505041,
        0.7896072 , 1.01443197, 0.50029365, 0.2064201 , 0.05657355,
        1.07690929, 0.15518115, 0.72732697, 1.16880439, 0.91844946,
        0.91103119, 0.95800184, 0.70710904, 0.78305163, 0.99937218,
        0.27509978, 0.84550429, 0.88868384, 0.73913253, 0.86203198,
        0.33367572, 0.54693282, 1.14281529, 0.44485107, 0.9168843 ,
        0.85230748, 0.9233973 , 0.62067681, 1.10763143, 0.97248548,
        0.7903107 , 0.90984268, 0.58105798, 0.80486965, 0.45936487,
        0.84656906, 0.6400416 , 1.12646067, 0.56519032, 0.34305022,
        1.18440395, 0.82146928, 0.96972314, 0.75179911, 0.69195341,
        1.14951572, 0.49627824, 1.20876987, 0.68

#### 53. How to convert a float (32 bits) array into an integer (32 bits) array in place?

In [72]:
a = np.random.uniform(low=1, high=10, size=20).astype(np.int32)
a

array([5, 7, 6, 3, 7, 3, 3, 7, 6, 8, 6, 6, 1, 4, 3, 3, 9, 4, 9, 6],
      dtype=int32)

#### 54. How to read the following file?
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [73]:
from io import StringIO
text = StringIO('''1, 2, 3, 4, 5
                6,  ,  , 7, 8
                ,  , 9,10,11
                ''')
np.genfromtxt(text, delimiter=",")

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6., nan, nan,  7.,  8.],
       [nan, nan,  9., 10., 11.]])

#### 55. What is the equivalent of enumerate for numpy arrays?

In [74]:
for idx, value in np.ndenumerate(np.arange(20, 10, -1)):
    print(idx, value)

(0,) 20
(1,) 19
(2,) 18
(3,) 17
(4,) 16
(5,) 15
(6,) 14
(7,) 13
(8,) 12
(9,) 11


#### 56. Generate a generic 2D Gaussian-like array 


In [75]:
def generate_2d_gaussian(kernel_size, sigma=1, mu=0):
    """
    Generates a 2D Gaussian array.

    Args:
        kernel_size (int): The size of the square Gaussian array (e.g., 5 for a 5x5 array).
        sigma (float): The standard deviation of the Gaussian distribution.
        mu (float): The mean of the Gaussian distribution (typically 0 for centering).

    Returns:
        numpy.ndarray: A 2D NumPy array representing the Gaussian.
    """
    # Create 1D arrays for x and y coordinates, centered around 0
    x = np.linspace(-(kernel_size // 2), kernel_size // 2, kernel_size)
    y = np.linspace(-(kernel_size // 2), kernel_size // 2, kernel_size)

    # Create 2D coordinate grids
    x_grid, y_grid = np.meshgrid(x, y)

    # Calculate the distance from the center
    distance_squared = x_grid**2 + y_grid**2

    # Apply the Gaussian function
    gaussian_array = np.exp(-(distance_squared / (2.0 * sigma**2)))

    # Normalize the array so its sum is 1 (optional, for kernels)
    gaussian_array /= np.sum(gaussian_array)

    return gaussian_array
kernel_size = 5
sigma_value = 1.0
generate_2d_gaussian(kernel_size, sigma=sigma_value)

array([[0.00296902, 0.01330621, 0.02193823, 0.01330621, 0.00296902],
       [0.01330621, 0.0596343 , 0.09832033, 0.0596343 , 0.01330621],
       [0.02193823, 0.09832033, 0.16210282, 0.09832033, 0.02193823],
       [0.01330621, 0.0596343 , 0.09832033, 0.0596343 , 0.01330621],
       [0.00296902, 0.01330621, 0.02193823, 0.01330621, 0.00296902]])

#### 57. How to randomly place p elements in a 2D array?

In [76]:
a = np.arange(20).reshape(-1, 2)
idx = np.random.randint(0, len(a))
# a[idx] = 1000 # will not work because, not sure if use for row or column
# alternate solution would be flatten it, then put the index,
#  then shape it back, but that is not as elegant at np.put
np.put(a, idx, 1000)
a

array([[   0, 1000],
       [   2,    3],
       [   4,    5],
       [   6,    7],
       [   8,    9],
       [  10,   11],
       [  12,   13],
       [  14,   15],
       [  16,   17],
       [  18,   19]])

#### 58. Subtract the mean of each row of a matrix

In [77]:
a = np.arange(20).reshape(-1, 2)
a - a.mean(axis=1, keepdims=True)
# other way is longer and use np.expand_dims
# a - np.expand_dims(a.mean(axis=1), axis=1)

array([[-0.5,  0.5],
       [-0.5,  0.5],
       [-0.5,  0.5],
       [-0.5,  0.5],
       [-0.5,  0.5],
       [-0.5,  0.5],
       [-0.5,  0.5],
       [-0.5,  0.5],
       [-0.5,  0.5],
       [-0.5,  0.5]])

#### 59. How to sort an array by the nth column?

In [78]:
# create a random matrix
a = np.random.uniform(0, 10, size=20).reshape((-1, 4))
# use np.argsort to sort the index for any column, then use that as the indices for the main matrix
column = 3 # get the fourth column, only that column should be sorted
a[np.argsort(a[:, column], axis=0)]

array([[5.52764967, 5.72292469, 9.80331584, 0.75346256],
       [0.43603772, 9.94550511, 4.69944514, 2.79560342],
       [8.83494022, 7.47718774, 9.53071847, 3.30750305],
       [2.30185268, 4.9919338 , 5.72004199, 7.68554014],
       [3.50078408, 6.45103362, 6.6892406 , 8.64167565]])

#### 60. How to tell if a given 2D array has null columns?

In [79]:
arr = np.array([[1, 2, np.nan],
                [4, 5, np.nan],
                [7, 8, np.nan]])

# Check if any column is entirely NaN
has_null_columns = np.any(np.all(np.isnan(arr), axis=0))
print(has_null_columns)

True


#### 61. Find the nearest value from a given value in an array

In [ ]:
np.random.seed(42)
a = np.random.uniform(low=1, high=100, size=10).astype(np.int64)
a
p = 50
# find their absoluate difference, then find the smallest index
a[np.argmin(np.abs(a - p))]

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator?

In [82]:
a = np.random.randint(0, 100, (1, 3))
b = np.random.randint(0, 100, (3, 1))
print("a:")
print(a)
print("b")
print(b)
result = np.zeros((3, 3), dtype=a.dtype) 
it = np.nditer([a, b, result], op_flags=[["readonly"], ["readonly"], ["writeonly"]])
for x, y, z in it:
    z[...] = x + y
print("result")
print (result)


a:
[[84 31 86]]
b
[[32]
 [66]
 [17]]
result
[[116  63 118]
 [150  97 152]
 [101  48 103]]


#### 63. Create an array class that has a name attribute

In [83]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.name = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

In [84]:
og = np.random.randint(1, 20, 10)
index_array = np.random.randint(0, len(og), 20)
print(og)
print(index_array)
np.add.at(og, index_array, 1)
print(og)

[10  3  8 14 18 15  2 10  2 17]
[7 0 8 5 6 9 6 9 2 1 8 7 9 6 8 3 3 0 7 2]
[12  4 10 16 18 16  5 13  5 20]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)?

In [85]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors

In [86]:
w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
print(n)

64


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once?

In [87]:
A = np.random.randint(0,10,(3,4,3,4))
# solution by passing a tuple of axes (introduced in numpy 1.7.0)
sum = A.sum(axis=(-2,-1))
print(sum)

[[69 65 36 43]
 [53 51 52 59]
 [68 65 71 32]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices?

In [88]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)


[0.40678389 0.53061981 0.51665257 0.43630842 0.36996798 0.55552704
 0.63178396 0.52144535 0.40872053 0.43242245]


#### 69. How to get the diagonal of a dot product?

In [89]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
np.sum(A * B.T, axis=1)

array([0.81181729, 1.52798362, 1.52066476, 2.02974992, 1.26127083])

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value?

In [92]:
a = np.array([1,2,3,4,5])
thrice = 3
new_arr = np.zeros(a.size * (thrice + 1))
new_arr[::thrice+1] = a
print(new_arr)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5. 0. 0. 0.]


#### 71. Consider an array of dimension (5,5,3), how to multiply it by an array with dimensions (5,5)?

In [93]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array?

In [94]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles 

In [95]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 2, 31) ( 2, 60) ( 5, 58) ( 5, 75) ( 8, 47) ( 8, 56) (14, 47) (14, 88)
 (16, 60) (16, 93) (21, 22) (21, 78) (22, 78) (25, 38) (25, 79) (26, 71)
 (26, 90) (31, 60) (38, 79) (40, 42) (40, 64) (42, 64) (47, 56) (47, 88)
 (49, 70) (49, 81) (58, 75) (60, 93) (70, 81) (71, 90)]


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C?

In [96]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array?

In [97]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1])


In [98]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.strides[0], a.strides[0])
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace?

In [99]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([-0.32442651, -0.48566378, -0.21685217, -0.49273968,  0.31104316,
        0.22106913, -0.56051375, -0.60293856,  0.83484365,  0.96611685,
       -0.33305314,  0.83113205,  0.65719277,  0.60557749, -0.01867552,
        0.59777173,  0.63823739,  0.97871198, -0.53309003,  0.72823781,
       -0.13751957,  0.40059991,  0.63402391,  0.30629083,  0.48506975,
        0.13351652, -0.38032722,  0.89814788,  0.63348414,  0.8394532 ,
       -0.93562521, -0.14783064, -0.64068361,  0.46665261, -0.79079937,
       -0.25796934,  0.18804895, -0.20112591,  0.74506125,  0.37370558,
       -0.07846451, -0.28089416,  0.56648024, -0.98373327, -0.66615562,
       -0.15994864, -0.94663917, -0.02520644, -0.89431932, -0.50351463,
        0.56530707,  0.18894515,  0.47436033, -0.44354305, -0.53325727,
       -0.3683855 , -0.09117385,  0.19585701, -0.96854502,  0.94397234,
        0.75228412, -0.1974783 , -0.51164512, -0.91520647,  0.01906177,
        0.4682363 , -0.72665139,  0.11883569,  0.74186714, -0.04

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])?

In [102]:
P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))

def distance(P0,P1,p):
    #Author: Hemanth Pasupuleti
    #Reference: https://mathworld.wolfram.com/Point-LineDistance2-Dimensional.html

    v = P1- P0 
    v[:,[0,1]] = v[:,[1,0]]
    v[:,1]*=-1 
    norm = np.linalg.norm(v,axis=1)   
    r = P0 - p
    d = np.abs(np.einsum("ij,ij->i",r,v)) / norm 

    return d

print(distance(P0, P1, p))

[12.74739577 12.81746349  1.61489261  1.72798742  9.40926301  0.92305741
  4.61668705  9.45522241  1.8946516  11.6297799 ]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])?


In [103]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 0.31631584  0.41230366  9.88064062  8.6567395   6.49961247 10.92610797
  13.3611439  10.5212703  10.20736076  0.30667874]
 [16.87334272  6.17718888  3.63040757  8.12610802  7.6037295   1.90784307
   3.00230311  1.71083883  0.22949833  9.89779022]
 [ 2.30904409  1.35599559  8.46312558  6.70088377  4.99810401  9.6025598
  12.36850132  9.27978444  9.26434554  1.11717134]
 [ 2.31913714  7.7130641   0.87991447  4.36488057  2.12403937  1.5667966
   3.13552211  0.89480788  0.10545914  5.98221229]
 [17.01517338  5.66846041  4.21213054  8.41294612  8.16214077  2.51163065
   2.34597663  2.33097581  0.4319959   9.54809286]
 [ 3.21932986  9.4175436   5.58643659 10.03628984  2.76922138  6.05800375
   6.82836993  5.1933219   3.46333095  9.22031808]
 [14.78516947  1.71406851  7.90799871  7.84600863 11.44225166  6.62851503
   2.97710715  6.78346238  5.90618903  2.99983677]
 [ 1.70307796  2.72576295 10.27743425  7.7203443   6.75369309 11.47100966
  14.35522444 11.18711656 11.2610055   1.98174172]
 [

#### 80. Consider an arbitrary array, write a function that extracts a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary)


In [104]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = tuple([slice(start,stop) for start,stop in zip(R_start,R_stop)])
z = tuple([slice(start,stop) for start,stop in zip(Z_start,Z_stop)])
R[r] = Z[z]
print(Z)
print(R)

[[8 6 1 3 8 2 7 0 7 6]
 [9 2 1 3 0 8 7 7 7 8]
 [2 6 0 0 7 6 8 5 8 7]
 [0 7 9 4 8 8 0 2 2 2]
 [9 5 7 2 2 5 6 6 7 4]
 [5 5 8 8 2 4 6 0 2 6]
 [2 5 7 7 7 0 2 4 5 2]
 [6 5 5 1 9 5 9 4 2 0]
 [8 7 5 6 1 5 4 9 0 1]
 [8 6 4 8 6 6 4 4 2 3]]
[[0 0 0 0 0]
 [0 8 6 1 3]
 [0 9 2 1 3]
 [0 2 6 0 0]
 [0 0 7 9 4]]


#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?


In [105]:
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank

In [107]:
Z = np.random.uniform(0,1,(10,10))
rank = np.linalg.matrix_rank(Z)
print(rank)

10


#### 83. How to find the most frequent value in an array?

In [108]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

1


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix

In [109]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)


[[[[3 3 4]
   [1 1 3]
   [0 2 4]]

  [[3 4 3]
   [1 3 2]
   [2 4 0]]

  [[4 3 1]
   [3 2 4]
   [4 0 2]]

  [[3 1 0]
   [2 4 3]
   [0 2 2]]

  [[1 0 1]
   [4 3 0]
   [2 2 4]]

  [[0 1 4]
   [3 0 0]
   [2 4 1]]

  [[1 4 3]
   [0 0 4]
   [4 1 2]]

  [[4 3 2]
   [0 4 4]
   [1 2 4]]]


 [[[1 1 3]
   [0 2 4]
   [2 3 2]]

  [[1 3 2]
   [2 4 0]
   [3 2 1]]

  [[3 2 4]
   [4 0 2]
   [2 1 2]]

  [[2 4 3]
   [0 2 2]
   [1 2 1]]

  [[4 3 0]
   [2 2 4]
   [2 1 0]]

  [[3 0 0]
   [2 4 1]
   [1 0 1]]

  [[0 0 4]
   [4 1 2]
   [0 1 2]]

  [[0 4 4]
   [1 2 4]
   [1 2 0]]]


 [[[0 2 4]
   [2 3 2]
   [0 0 0]]

  [[2 4 0]
   [3 2 1]
   [0 0 2]]

  [[4 0 2]
   [2 1 2]
   [0 2 4]]

  [[0 2 2]
   [1 2 1]
   [2 4 1]]

  [[2 2 4]
   [2 1 0]
   [4 1 4]]

  [[2 4 1]
   [1 0 1]
   [1 4 4]]

  [[4 1 2]
   [0 1 2]
   [4 4 1]]

  [[1 2 4]
   [1 2 0]
   [4 1 3]]]


 [[[2 3 2]
   [0 0 0]
   [1 3 1]]

  [[3 2 1]
   [0 0 2]
   [3 1 4]]

  [[2 1 2]
   [0 2 4]
   [1 4 4]]

  [[1 2 1]
   [2 4 1]
   [4 4 1]]

  [[2 1 0]
   

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i]

In [110]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 0  6  7  8  8]
 [ 6  9  6 16 10]
 [ 7  6  6 42  5]
 [ 8 16 42  0  8]
 [ 8 10  5  8  4]]


#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1))

In [111]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)?

In [112]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays?

In [113]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 1 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 1 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1

#### 89. How to get the n largest values of an array

In [114]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

print (Z[np.argsort(Z)[-n:]])

[9995 9996 9997 9998 9999]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combination of every item)

In [115]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array?

In [116]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


C:\Users\thotc\AppData\Local\Temp\ipykernel_1928\100570611.py:3: DeprecationWarning: numpy.core is deprecated and has been renamed to numpy._core. The numpy._core namespace contains private NumPy internals and its use is discouraged, as NumPy internals can change without warning in any release. In practice, most real-world usage of numpy.core is to access functionality in the public NumPy API. If that is the case, use the public NumPy API. If not, you are using NumPy internals. If you would still like to access an internal attribute, use numpy._core.records.
  R = np.core.records.fromarrays(Z.T,


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods

In [120]:
x = np.random.rand(int(5e4))

np.power(x,3)
x*x*x
np.einsum('i,i,i->i',x,x,x)

array([1.91001011e-02, 6.36601392e-01, 8.96222901e-01, 1.56828613e-01,
       3.50849806e-04, 5.50449914e-01, 4.70195921e-03, 6.59840553e-02,
       7.87229771e-03, 1.63400377e-01, 1.15707337e-02, 6.73872592e-01,
       8.58720751e-01, 6.21693175e-01, 8.75692159e-03, 5.01734787e-02,
       4.61100720e-02, 2.58187200e-01, 8.27007460e-02, 1.47665226e-01,
       4.54596601e-03, 6.09570187e-03, 4.04718819e-02, 3.40901578e-03,
       9.14346560e-03, 4.82532935e-01, 6.74436064e-01, 1.14799786e-03,
       4.08146207e-02, 1.57049048e-03, 6.56675424e-02, 3.28184276e-01,
       1.10773379e-02, 5.00345412e-03, 3.38516552e-01, 8.89553682e-01,
       6.27220862e-02, 3.08995589e-04, 1.59719299e-01, 5.29527722e-01,
       3.94292936e-01, 2.22088749e-01, 3.05444575e-01, 3.04266648e-02,
       3.40073566e-04, 3.87445235e-01, 5.28045270e-02, 3.14274845e-04,
       4.54684495e-01, 8.23334721e-03, 5.64365722e-01, 1.21535921e-01,
       1.13256974e-01, 3.35156459e-03, 8.02653115e-03, 5.25631084e-02,
      

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B?

In [121]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[0 1 2 3 4 5 6 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3])

In [122]:
Z = np.random.randint(0,5,(10,3))
print(Z)
# solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)
# soluiton for numerical arrays only, will work for any number of columns in Z
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[0 4 4]
 [0 1 4]
 [2 4 2]
 [2 3 0]
 [2 2 4]
 [0 1 4]
 [1 4 3]
 [3 1 3]
 [1 0 0]
 [1 0 0]]
[[0 4 4]
 [0 1 4]
 [2 4 2]
 [2 3 0]
 [2 2 4]
 [0 1 4]
 [1 4 3]
 [3 1 3]
 [1 0 0]
 [1 0 0]]
[[0 4 4]
 [0 1 4]
 [2 4 2]
 [2 3 0]
 [2 2 4]
 [0 1 4]
 [1 4 3]
 [3 1 3]
 [1 0 0]
 [1 0 0]]


#### 95. Convert a vector of ints into a matrix binary representation 

In [123]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows?

In [124]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

[[0 0 0]
 [0 0 1]
 [0 1 0]
 [0 1 1]
 [1 0 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function

In [125]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)

array([[0.26200094, 0.2143968 , 0.22052592, 0.17385613, 0.0351299 ,
        0.23254623, 0.06521015, 0.03493248, 0.01932823, 0.33554422],
       [0.53423499, 0.4371674 , 0.44966505, 0.35450265, 0.07163188,
        0.47417513, 0.13296725, 0.07122933, 0.03941137, 0.68419397],
       [0.05631039, 0.0460791 , 0.0473964 , 0.03736592, 0.00755027,
        0.04997986, 0.01401525, 0.00750784, 0.00415411, 0.07211664],
       [0.06078046, 0.04973698, 0.05115885, 0.04033213, 0.00814963,
        0.05394739, 0.01512782, 0.00810383, 0.00448387, 0.07784144],
       [0.17897791, 0.1464586 , 0.15064553, 0.11876449, 0.02399791,
        0.15885683, 0.04454632, 0.02386305, 0.01320349, 0.22921675],
       [0.40250869, 0.32937505, 0.33879115, 0.26709294, 0.05396961,
        0.35725779, 0.10018152, 0.05366632, 0.02969371, 0.51549228],
       [0.49097542, 0.40176786, 0.41325351, 0.32579687, 0.06583151,
        0.4357789 , 0.12220025, 0.06546155, 0.03622005, 0.6287915 ],
       [0.16659676, 0.13632704, 0.1402243

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples

In [126]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. 


In [127]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means).




In [128]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.31343235  0.11035518]
