# 100 excercises in Numpy
- got the idea from this github: https://github.com/rougier/numpy-100

In [32]:
import numpy as np

#### 1. Create a numpy array

In [ ]:
a = np.arange(15).reshape(3, 5)

In [ ]:
print(a)

#### 2. Find the shape of an numpy array

In [ ]:
a.shape

#### 3. Find the dimension and data type of a numpy array

In [ ]:
a.ndim

In [ ]:
a.dtype.name

#### 4. How to find the memory size of any array

In [ ]:
a.size

# Printing arrays
#### When you print an array, NumPy displays it in a similar way to nested lists, but with the following layout:

- the last axis is printed from left to right,

- the second-to-last is printed from top to bottom,

- the rest are also printed from top to bottom, with each slice separated from the next by an empty line.
- If an array is too large to be printed, NumPy automatically skips the central part of the array and only prints the corners:

#### One-dimensional arrays are then printed as rows, bidimensionals as matrices and tridimensionals as lists of matrices.

In [ ]:
print(np.arange(5)) # 1d array

In [ ]:
print(np.arange(6).reshape(2, 3)) # 2d array

In [ ]:
print(np.arange(24).reshape(3, 2, 4)) # 3d array

In [ ]:
np.atleast_2d([2, 3, 4]).shape

In [ ]:
np.core # where np is located

#### 5. Get documentation on a function

In [ ]:
np.info(np.add)

#### 6. Create a null vector of size 10 but the fifth value which is 1

In [ ]:
a = np.zeros(10)
a[4] = 1
a

#### 7. Create a vector with values ranging from 10 to 49

In [ ]:
a = np.arange(10, 50)
a

#### 8. Reverse a vector (first element becomes last)

In [ ]:
a = np.arange(10)
print(a)
print(a[::-1])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
print(np.arange(9).reshape((3, 3)))

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0]

In [ ]:
np.nonzero(np.array([1, 2, 0, 0, 4, 0]))
# np.where(np.array([1, 2, 0, 0, 4, 0] != 0))

#### 11. Create a 3x3 identity matrix

In [ ]:
A = np.diag(np.ones(3))
A

In [ ]:
np.eye(3)

In [ ]:
np.identity(3)

#### 12. Create a 3x3x3 array with random values

In [ ]:
np.random.random(27).reshape((3, 3, 3))

#### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [ ]:
a = np.random.random(100).reshape((10, 10))
print(a.min())
print(a.max())

#### 14. Create a random vector of size 30 and find the mean value

In [ ]:
a = np.random.random(30)
a.mean()

#### 15. Create a 2d array with 1 on the border and 0 inside

In [ ]:
np.eye(9)

#### 16. How to add a border (filled with 0's) around an existing array?

In [ ]:
# make the array with ones first
ones = np.ones((5, 5))
# set the zeros 1 size smaller than the arrays
ones[1:-1, 1:-1] = 0
print(ones)


#### 17. What is the result of the following expression?
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [ ]:
M = np.zeros((5, 5))
a = np.arange(1, 5)
M[a, a- 1] = a
M

In [ ]:
M[a -1, a] = a
M

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [ ]:
matrix = np.zeros((8, 8))
matrix[1::2, ::2] = 1
matrix[::2, 1::2] = 1
matrix


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [ ]:
a = np.arange(0, 6*7*8).reshape((6, 7, 8))
a[np.unravel_index(99, (6, 7, 8))]

#### 21. Create a checkerboard 8x8 matrix using the tile function

In [ ]:
a = np.array([[0, 1], [1, 0]])
np.tile(a, (4, 4))

#### 22. Normalize a 5x5 random matrix

In [ ]:
M = np.random.random((5, 5))
(M - M.mean()) / M.std() # Z-score normalization, There are other methods beside this

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA)

In [ ]:
RGBA = np.dtype([
    ('r', np.uint8),
    ('g', np.uint8),
    ('b', np.uint8),
    ('a', np.uint8)
])

print(RGBA)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

In [ ]:
np.random.seed(42)
A = np.random.randint(0, 10, size=(5, 3)) 
B = np.random.randint(0, 10, size=(3,2))
print(A)
print(B)
print(A @ B) 

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place.

In [ ]:
a = np.arange(10)

a[ (a > 3) & (a < 8)] *= -1
a

#### 26. What is the output of the following script?
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [33]:
# trick question, first one is the regular sum, add from 0-5, then add -1
# 2nd question, add from 0-5, with axis -1, which means the only axis or the last axis
# print(sum(range(5),-1)) # 
# from numpy import *
# print(sum(range(5),-1))
# should be 9 and 10

#### 27. Consider an integer vector Z, which of these expressions are legal?
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [40]:
Z = np.array([1, 2,3])
Z**Z,
2 << Z >> 2
1j*Z
Z/1/1
# Z<Z>Z # not legal, can't do bitwise left and right shift with vector

array([1., 2., 3.])

#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
# error np.array(0) / np.array(0)
# error np.array(0) // np.array(0)
# error np.array([np.nan]).astype(int).astype(float)


#### 29. How to round away from zero a float array ?

In [49]:
np.random.seed(42)
Z = np.random.uniform(-10, 10, 10)
np.copysign(np.ceil(np.abs(Z)), Z)

array([-3., 10.,  5.,  2., -7., -7., -9.,  8.,  3.,  5.])

#### 30. How to find common values between two arrays?

In [51]:
np.intersect1d(np.array([1, 2, 3]), np.array([10, 3, 4]))

array([3])

#### 31. How to ignore all numpy warnings (not recommended)?

In [52]:
# np.seterr(all='ignore')

#### 32. Is the following expressions true?
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [54]:
# np.sqrt(-1) == np.emath.sqrt(-1), No

#### 33. How to get the dates of yesterday, today and tomorrow?

In [ ]:
today = np.datetime64('today', 'D')
yesterday = today - np.timedelta64(1, 'D')
tommorrow = today + np.timedelta64(1, 'D')
print(f"today: {today}")
print(f"yesterday: {yesterday}")
print(f"tommorrow: {tommorrow}")

#### 34. How to get all the dates corresponding to the month of July 2016?

In [56]:
np.arange(np.datetime64("2016-07-01"), np.datetime64("2016-08-01"), dtype="datetime64[D]")

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? 

In [ ]:
A = np.arange(5, dtype='float64')
B = np.arange(5, dtype='float64')
np.multiply(np.add(A, B, out=B), np.negative(np.divide(A, 2, out=A)), out=A)

array([ -0.,  -1.,  -4.,  -9., -16.])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods

In [ ]:
np.random.seed(42)
a = np.random.random(5) * 5
print(np.floor_divide(a,  1)) # floor divide
print(np.floor(a)) # rounding, floor and celing
print(np.astype(a, np.int64)) # convert from float to int
print(np.trunc(a)) # actually truncate the values


[1. 4. 3. 2. 0.]
[1. 4. 3. 2. 0.]
[1 4 3 2 0]
[1. 4. 3. 2. 0.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4

In [ ]:
np.tile(np.arange(5), 5).reshape((5, 5)) # my way

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [77]:
np.tile(np.arange(5), (5, 1))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [ ]:
# create all zeros matrix, then all each row from 0-4
Z = np.zeros((5,5), dtype='int64') # include the dtype, otherwise np will give float
Z += np.arange(5)
Z

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array

In [84]:
np.fromiter((x for x in range(10)), dtype=np.int64)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded

In [ ]:
np.linspace(0, 1, 11,endpoint=False)[1:] # need to use endpoint as false, then take out the initial value.
# there are so many ways to achieve this without this weird answer

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it

In [89]:
np.sort(np.random.random(10))

array([0.02058449, 0.05808361, 0.15599452, 0.18182497, 0.21233911,
       0.60111501, 0.70807258, 0.83244264, 0.86617615, 0.96990985])

#### 41. How to sum a small array faster than np.sum?

In [94]:
# instead of using np.sum, use np.add.reduce
a = np.arange(1, 10)
np.add.reduce(a)

np.int64(45)

#### 42. Consider two random arrays A and B, check if they are equal

In [ ]:
np.array_equal([1, 2], [1, 2]) #
# use np.allclose if they are floats

True

#### 43. Make an array immutable (read-only)

In [ ]:
a = np.arange(1, 6)
a.flags.writeable = False # need to set this flag to false
a[3] = 10 # 

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates

In [102]:
a = np.random.random(20).reshape((10, 2))
# need to use the r = sqrt(x^2 + y^2), theta = arctan(y/x)
def cart2pol(coord):
    x, y = coord
    rho = np.hypot(x, y)
    phi = np.arctan2(y, x)
    return rho, phi
print(a)

b = np.apply_along_axis(cart2pol, 1, a)
print(b)

[[0.87146059 0.80367208]
 [0.18657006 0.892559  ]
 [0.53934224 0.80744016]
 [0.8960913  0.31800347]
 [0.11005192 0.22793516]
 [0.42710779 0.81801477]
 [0.86073058 0.00695213]
 [0.5107473  0.417411  ]
 [0.22210781 0.11986537]
 [0.33761517 0.9429097 ]]
[[1.18546715 0.74495268]
 [0.91184974 1.36473501]
 [0.97100446 0.98189501]
 [0.9508448  0.34101423]
 [0.25311236 1.12098598]
 [0.92280508 1.08960403]
 [0.86075866 0.00807684]
 [0.65961713 0.68517434]
 [0.25238777 0.49487928]
 [1.00153019 1.22696212]]


#### 45. Create random vector of size 10 and replace the maximum value by 0

In [ ]:
a = np.ones(10)
a[7] = 10
a[a.argmax()] = 0 # argmax returns the index
a.max() # max returns the value


np.float64(1.0)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area

In [112]:
A = np.zeros((10, 10), [('x', float), ('y', float)])
print(A)
x = np.linspace(0, 1, 10)
y = np.linspace(0, 1, 10)
A['x'], A['y'] = np.meshgrid(x, y)
print(A)

[[(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)
  (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)
  (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)
  (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)
  (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)
  (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)
  (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)
  (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)
  (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)
  (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)
  (0., 0.) (0., 0.)]]
[[(0.        , 0.        ) (0.11111111, 0.       

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [ ]:
np.random.seed(42)
x = np.random.random(5) * np.arange(1, 6)
y = np.random.random(5) * np.arange(1, 6)
print(x)
print(y)
cauchy = 1.0 / (x.reshape((-1, 1)) - y) # the reshape (-1, 1) turns it into a column
print(cauchy)

[0.37454012 1.90142861 2.19598183 2.39463394 0.7800932 ]
[0.15599452 0.11616722 2.59852844 2.40446005 3.54036289]
[[   4.57570414    3.87037503   -0.44964265   -0.49263027   -0.31587365]
 [   0.57292338    0.56014206   -1.43451478   -1.98794734   -0.61015259]
 [   0.49019913    0.48081209   -2.48418437   -4.7966641    -0.74383672]
 [   0.4466999     0.43889164   -4.90449717 -101.76967093   -0.87280678]
 [   1.60231071    1.50619201   -0.54992335   -0.61562448   -0.36228344]]


In [124]:
x_reshape = x.reshape((-1, 1))
x.shape

(5,)

#### 48. Print the minimum and maximum representable values for each numpy scalar type

In [129]:
np.iinfo(np.int64) # use the iinfo function

iinfo(min=-9223372036854775808, max=9223372036854775807, dtype=int64)

#### 49. How to print all the values of an array?

In [ ]:
print(np.arange(10)) # not really sure what the questions here is

[0 1 2 3 4 5 6 7 8 9]


#### 50. How to find the closest value (to a given scalar) in a vector?

In [ ]:
arr = np.arange(0, 20)
scalar = 7
# find the differences between scalar and vector
# get the absolute value
# get the index with argmin, then use it to get the value from the array
arr[np.argmin(np.abs(arr - scalar))]

np.int64(7)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances 

#### 53. How to convert a float (32 bits) array into an integer (32 bits) array in place?

#### 54. How to read the following file?
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays?

#### 56. Generate a generic 2D Gaussian-like array 


#### 57. How to randomly place p elements in a 2D array?

#### 58. Subtract the mean of each row of a matrix

#### 59. How to sort an array by the nth column?

#### 60. How to tell if a given 2D array has null columns?

#### 61. Find the nearest value from a given value in an array

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator?

#### 63. Create an array class that has a name attribute

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)?

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once?

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices?

#### 69. How to get the diagonal of a dot product?

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value?

#### 71. Consider an array of dimension (5,5,3), how to multiply it by an array with dimensions (5,5)?

#### 72. How to swap two rows of an array?

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles 

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C?

#### 75. How to compute averages using a sliding window over an array?

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1])


#### 77. How to negate a boolean, or to change the sign of a float inplace?

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])?

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])?


#### 80. Consider an arbitrary array, write a function that extracts a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary)


#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?


#### 82. Compute a matrix rank

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i]

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1))

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)?

#### 88. How to implement the Game of Life using numpy arrays?

#### 89. How to get the n largest values of an array

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combination of every item)

#### 91. How to create a record array from a regular array?

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B?

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3])

#### 95. Convert a vector of ints into a matrix binary representation 

#### 96. Given a two dimensional array, how to extract unique rows?

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. 


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means).


