# 100 excercises in Numpy
- got the idea from this github: https://github.com/rougier/numpy-100

In [2]:
import numpy as np

#### 1. Create a numpy array

In [5]:
a = np.arange(15).reshape(3, 5)

In [6]:
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


#### 2. Find the shape of an numpy array

In [7]:
a.shape

(3, 5)

#### 3. Find the dimension and data type of a numpy array

In [8]:
a.ndim

2

In [9]:
a.dtype.name

'int64'

#### 4. How to find the memory size of any array

In [10]:
a.size

15

# Printing arrays
#### When you print an array, NumPy displays it in a similar way to nested lists, but with the following layout:

- the last axis is printed from left to right,

- the second-to-last is printed from top to bottom,

- the rest are also printed from top to bottom, with each slice separated from the next by an empty line.
- If an array is too large to be printed, NumPy automatically skips the central part of the array and only prints the corners:

#### One-dimensional arrays are then printed as rows, bidimensionals as matrices and tridimensionals as lists of matrices.

In [11]:
print(np.arange(5)) # 1d array

[0 1 2 3 4]


In [12]:
print(np.arange(6).reshape(2, 3)) # 2d array

[[0 1 2]
 [3 4 5]]


In [13]:
print(np.arange(24).reshape(3, 2, 4)) # 3d array

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]]


In [14]:
np.atleast_2d([2, 3, 4]).shape

(1, 3)

In [15]:
np.core # where np is located

<module 'numpy.core' from 'c:\\Users\\thotc\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\numpy\\core\\__init__.py'>

#### 5. Get documentation on a function

In [16]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

#### 6. Create a null vector of size 10 but the fifth value which is 1

In [17]:
a = np.zeros(10)
a[4] = 1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49

In [18]:
a = np.arange(10, 50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last)

In [19]:
a = np.arange(10)
print(a)
print(a[::-1])

[0 1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]


In [21]:
np.flip(a)

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8

In [22]:
print(np.arange(9).reshape((3, 3)))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0]

In [23]:
np.nonzero(np.array([1, 2, 0, 0, 4, 0]))
# np.where(np.array([1, 2, 0, 0, 4, 0] != 0))

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix

In [24]:
A = np.diag(np.ones(3))
A

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values

In [27]:
np.random.random(27).reshape((3, 3, 3))

array([[[0.81280139, 0.12906478, 0.5371271 ],
        [0.83667749, 0.21322253, 0.77317452],
        [0.83028679, 0.57490789, 0.97617038]],

       [[0.35326133, 0.21101476, 0.12910688],
        [0.68108943, 0.11224819, 0.9412858 ],
        [0.41700881, 0.45871955, 0.6669299 ]],

       [[0.16653648, 0.08004754, 0.16723162],
        [0.16073305, 0.74156104, 0.81523465],
        [0.20828814, 0.96079549, 0.04142047]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [28]:
a = np.random.random(100).reshape((10, 10))
print(a.min())
print(a.max())

0.012820753753498226
0.9989102850331151


#### 14. Create a random vector of size 30 and find the mean value

In [29]:
a = np.random.random(30)
a.mean()

np.float64(0.4493625534793261)

#### 15. Create a 2d array with 1 on the border and 0 inside

In [30]:
np.eye(9)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array?

In [31]:
# make the array with ones first
ones = np.ones((5, 5))
# set the zeros 1 size smaller than the arrays
ones[1:-1, 1:-1] = 0
print(ones)


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 17. What is the result of the following expression?
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [32]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [33]:
M = np.zeros((5, 5))
a = np.arange(1, 5)
M[a, a- 1] = a
M

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.]])

In [34]:
M[a -1, a] = a
M

array([[0., 1., 0., 0., 0.],
       [1., 0., 2., 0., 0.],
       [0., 2., 0., 3., 0.],
       [0., 0., 3., 0., 4.],
       [0., 0., 0., 4., 0.]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [35]:
matrix = np.zeros((8, 8))
matrix[1::2, ::2] = 1
matrix[::2, 1::2] = 1
matrix


array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [36]:
a = np.arange(0, 6*7*8).reshape((6, 7, 8))
a[np.unravel_index(99, (6, 7, 8))]

np.int64(99)

#### 21. Create a checkerboard 8x8 matrix using the tile function

In [37]:
a = np.array([[0, 1], [1, 0]])
np.tile(a, (4, 4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix

In [38]:
M = np.random.random((5, 5))
(M - M.mean()) / M.std() # Z-score normalization, There are other methods beside this

array([[-1.63735503, -0.48398803,  0.79841703, -0.97726202, -0.02518043],
       [ 1.36542233,  0.09104465, -0.9971983 , -0.39321355,  1.10422969],
       [-0.53346183,  1.57913182, -0.38398128,  1.4920345 ,  1.14595883],
       [ 1.7413996 ,  0.24790421, -1.49986693, -0.1905428 , -0.41306488],
       [-0.07404881, -1.21559287,  0.71270959, -1.49736781,  0.04387233]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA)

In [39]:
RGBA = np.dtype([
    ('r', np.uint8),
    ('g', np.uint8),
    ('b', np.uint8),
    ('a', np.uint8)
])

print(RGBA)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

In [40]:
np.random.seed(42)
A = np.random.randint(0, 10, size=(5, 3)) 
B = np.random.randint(0, 10, size=(3,2))
print(A)
print(B)
print(A @ B) 

[[6 3 7]
 [4 6 9]
 [2 6 7]
 [4 3 7]
 [7 2 5]]
[[4 1]
 [7 5]
 [1 4]]
[[52 49]
 [67 70]
 [57 60]
 [44 47]
 [47 37]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place.

In [41]:
a = np.arange(10)

a[ (a > 3) & (a < 8)] *= -1
a

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9])

#### 26. What is the output of the following script?
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [42]:
# trick question, first one is the regular sum, add from 0-5, then add -1
# 2nd question, add from 0-5, with axis -1, which means the only axis or the last axis
# print(sum(range(5),-1)) # 
# from numpy import *
# print(sum(range(5),-1))
# should be 9 and 10

#### 27. Consider an integer vector Z, which of these expressions are legal?
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [43]:
Z = np.array([1, 2,3])
Z**Z,
2 << Z >> 2
1j*Z
Z/1/1
# Z<Z>Z # not legal, can't do bitwise left and right shift with vector

array([1., 2., 3.])

#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [44]:
# error np.array(0) / np.array(0)
# error np.array(0) // np.array(0)
# error np.array([np.nan]).astype(int).astype(float)


#### 29. How to round away from zero a float array ?

In [45]:
np.random.seed(42)
Z = np.random.uniform(-10, 10, 10)
np.copysign(np.ceil(np.abs(Z)), Z)

array([-3., 10.,  5.,  2., -7., -7., -9.,  8.,  3.,  5.])

#### 30. How to find common values between two arrays?

In [46]:
np.intersect1d(np.array([1, 2, 3]), np.array([10, 3, 4]))

array([3])

#### 31. How to ignore all numpy warnings (not recommended)?

In [47]:
# np.seterr(all='ignore')

#### 32. Is the following expressions true?
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [48]:
# np.sqrt(-1) == np.emath.sqrt(-1), No

#### 33. How to get the dates of yesterday, today and tomorrow?

In [49]:
today = np.datetime64('today', 'D')
yesterday = today - np.timedelta64(1, 'D')
tommorrow = today + np.timedelta64(1, 'D')
print(f"today: {today}")
print(f"yesterday: {yesterday}")
print(f"tommorrow: {tommorrow}")

today: 2025-10-14
yesterday: 2025-10-13
tommorrow: 2025-10-15


#### 34. How to get all the dates corresponding to the month of July 2016?

In [50]:
np.arange(np.datetime64("2016-07-01"), np.datetime64("2016-08-01"), dtype="datetime64[D]")

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? 

In [51]:
A = np.arange(5, dtype='float64')
B = np.arange(5, dtype='float64')
np.multiply(np.add(A, B, out=B), np.negative(np.divide(A, 2, out=A)), out=A)

array([ -0.,  -1.,  -4.,  -9., -16.])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods

In [52]:
np.random.seed(42)
a = np.random.random(5) * 5
print(np.floor_divide(a,  1)) # floor divide
print(np.floor(a)) # rounding, floor and celing
print(np.astype(a, np.int64)) # convert from float to int
print(np.trunc(a)) # actually truncate the values


[1. 4. 3. 2. 0.]
[1. 4. 3. 2. 0.]
[1 4 3 2 0]
[1. 4. 3. 2. 0.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4

In [53]:
np.tile(np.arange(5), 5).reshape((5, 5)) # my way

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [54]:
np.tile(np.arange(5), (5, 1))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [55]:
# create all zeros matrix, then all each row from 0-4
Z = np.zeros((5,5), dtype='int64') # include the dtype, otherwise np will give float
Z += np.arange(5)
Z

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array

In [56]:
np.fromiter((x for x in range(10)), dtype=np.int64)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded

In [57]:
np.linspace(0, 1, 11,endpoint=False)[1:] # need to use endpoint as false, then take out the initial value.
# there are so many ways to achieve this without this weird answer

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it

In [58]:
np.sort(np.random.random(10))

array([0.02058449, 0.05808361, 0.15599452, 0.18182497, 0.21233911,
       0.60111501, 0.70807258, 0.83244264, 0.86617615, 0.96990985])

#### 41. How to sum a small array faster than np.sum?

In [59]:
# instead of using np.sum, use np.add.reduce
a = np.arange(1, 10)
np.add.reduce(a)

np.int64(45)

#### 42. Consider two random arrays A and B, check if they are equal

In [60]:
np.array_equal([1, 2], [1, 2]) #
# use np.allclose if they are floats

True

#### 43. Make an array immutable (read-only)

In [61]:
a = np.arange(1, 6)
a.flags.writeable = False # need to set this flag to false
a[3] = 10 # 

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates

In [62]:
a = np.random.random(20).reshape((10, 2))
# need to use the r = sqrt(x^2 + y^2), theta = arctan(y/x)
def cart2pol(coord):
    x, y = coord
    rho = np.hypot(x, y)
    phi = np.arctan2(y, x)
    return rho, phi
print(a)

b = np.apply_along_axis(cart2pol, 1, a)
print(b)

[[0.18340451 0.30424224]
 [0.52475643 0.43194502]
 [0.29122914 0.61185289]
 [0.13949386 0.29214465]
 [0.36636184 0.45606998]
 [0.78517596 0.19967378]
 [0.51423444 0.59241457]
 [0.04645041 0.60754485]
 [0.17052412 0.06505159]
 [0.94888554 0.96563203]]
[[0.35524718 1.02830298]
 [0.67966596 0.68868891]
 [0.67762702 1.1265495 ]
 [0.32373914 1.12532471]
 [0.58499644 0.89404533]
 [0.81016721 0.24902584]
 [0.7844693  0.85592681]
 [0.60931797 1.49448884]
 [0.18251078 0.36443989]
 [1.35382015 0.79414505]]


#### 45. Create random vector of size 10 and replace the maximum value by 0

In [63]:
a = np.ones(10)
a[7] = 10
a[a.argmax()] = 0 # argmax returns the index
a.max() # max returns the value


np.float64(1.0)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area

In [64]:
A = np.zeros((10, 10), [('x', float), ('y', float)])
print(A)
x = np.linspace(0, 1, 10)
y = np.linspace(0, 1, 10)
A['x'], A['y'] = np.meshgrid(x, y)
print(A)

[[(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)
  (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)
  (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)
  (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)
  (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)
  (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)
  (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)
  (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)
  (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)
  (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)
  (0., 0.) (0., 0.)]]
[[(0.        , 0.        ) (0.11111111, 0.       

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [65]:
np.random.seed(42)
x = np.random.random(5) * np.arange(1, 6)
y = np.random.random(5) * np.arange(1, 6)
print(x)
print(y)
cauchy = 1.0 / (x.reshape((-1, 1)) - y) # the reshape (-1, 1) turns it into a column
print(cauchy)

[0.37454012 1.90142861 2.19598183 2.39463394 0.7800932 ]
[0.15599452 0.11616722 2.59852844 2.40446005 3.54036289]
[[   4.57570414    3.87037503   -0.44964265   -0.49263027   -0.31587365]
 [   0.57292338    0.56014206   -1.43451478   -1.98794734   -0.61015259]
 [   0.49019913    0.48081209   -2.48418437   -4.7966641    -0.74383672]
 [   0.4466999     0.43889164   -4.90449717 -101.76967093   -0.87280678]
 [   1.60231071    1.50619201   -0.54992335   -0.61562448   -0.36228344]]


In [66]:
x_reshape = x.reshape((-1, 1))
x.shape

(5,)

#### 48. Print the minimum and maximum representable values for each numpy scalar type

In [67]:
np.iinfo(np.int64) # use the iinfo function

iinfo(min=-9223372036854775808, max=9223372036854775807, dtype=int64)

#### 49. How to print all the values of an array?

In [68]:
# question is meant to ask, how to display all the values of an array if the array is very large.
# need to use set_printoptions
# https://numpy.org/doc/stable/user/quickstart.html#tricks-and-tips
import sys
np.set_printoptions(threshold=sys.maxsize)
print(np.arange(10000)) # not really sure what the questions here is

[   0    1    2    3    4    5    6    7    8    9   10   11   12   13
   14   15   16   17   18   19   20   21   22   23   24   25   26   27
   28   29   30   31   32   33   34   35   36   37   38   39   40   41
   42   43   44   45   46   47   48   49   50   51   52   53   54   55
   56   57   58   59   60   61   62   63   64   65   66   67   68   69
   70   71   72   73   74   75   76   77   78   79   80   81   82   83
   84   85   86   87   88   89   90   91   92   93   94   95   96   97
   98   99  100  101  102  103  104  105  106  107  108  109  110  111
  112  113  114  115  116  117  118  119  120  121  122  123  124  125
  126  127  128  129  130  131  132  133  134  135  136  137  138  139
  140  141  142  143  144  145  146  147  148  149  150  151  152  153
  154  155  156  157  158  159  160  161  162  163  164  165  166  167
  168  169  170  171  172  173  174  175  176  177  178  179  180  181
  182  183  184  185  186  187  188  189  190  191  192  193  194  195
  196 

#### 50. How to find the closest value (to a given scalar) in a vector?

In [ ]:
arr = np.arange(0, 20)
scalar = 7
# find the differences between scalar and vector
# get the absolute value
# get the index with argmin, then use it to get the value from the array
arr[np.argmin(np.abs(arr - scalar))]

np.int64(7)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b)

In [73]:
# Use tuples
position = np.dtype([("x", float), ("y", float)])
color = np.dtype([("r", float), ("g", float), ("b", float)])
a = np.zeros(33, [("position",  position), ("color",  color)])
a


array([((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.))],
      dtype=[('positio

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances 

In [ ]:
points = np.random.random((100,2))

diff = points[:, None, :] - points[None, :, :]

np.linalg.norm(diff, axis=-1) # another option is to use scipy.spatial.distance.cdist

array([[0.        , 0.478884  , 0.483133  , 0.22991055, 0.18690318,
        0.16470673, 0.55872264, 0.53010325, 0.51893227, 0.34864741,
        0.31043964, 0.20135775, 0.35480906, 0.71935065, 0.52379523,
        0.47128527, 0.48740742, 0.58333571, 0.30004177, 0.44507118,
        0.39847898, 0.48171817, 0.40258433, 0.38744305, 0.59510099,
        0.30543535, 0.44398157, 0.3322535 , 0.14865955, 0.4409743 ,
        0.28618554, 0.38772824, 0.19401609, 0.25305952, 0.18513526,
        0.49164165, 0.6224801 , 0.65661802, 0.17084287, 0.28099545,
        0.83486393, 0.43015221, 0.45452187, 0.52497857, 0.61106413,
        0.52233517, 0.05506412, 0.33479428, 0.37036159, 0.48788605,
        0.62318132, 0.58926829, 0.28727529, 0.53710851, 0.59072285,
        0.02270608, 0.42677423, 0.40872845, 0.0803712 , 0.46255525,
        0.20373112, 0.78555151, 0.82265198, 0.30695225, 0.59872172,
        0.22576813, 0.45564317, 0.16837941, 0.65233288, 0.18622256,
        0.17079383, 0.54026907, 0.48071787, 0.53

#### 53. How to convert a float (32 bits) array into an integer (32 bits) array in place?

In [76]:
a = np.random.uniform(low=1, high=10, size=20).astype(np.int32)
a

array([3, 9, 9, 6, 6, 5, 3, 3, 7, 7, 8, 8, 1, 5, 1, 5, 4, 8, 4, 2],
      dtype=int32)

#### 54. How to read the following file?
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [78]:
from io import StringIO
text = StringIO('''1, 2, 3, 4, 5
                6,  ,  , 7, 8
                ,  , 9,10,11
                ''')
np.genfromtxt(text, delimiter=",")

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6., nan, nan,  7.,  8.],
       [nan, nan,  9., 10., 11.]])

#### 55. What is the equivalent of enumerate for numpy arrays?

In [82]:
for idx, value in np.ndenumerate(np.arange(20, 10, -1)):
    print(idx, value)

(0,) 20
(1,) 19
(2,) 18
(3,) 17
(4,) 16
(5,) 15
(6,) 14
(7,) 13
(8,) 12
(9,) 11


#### 56. Generate a generic 2D Gaussian-like array 


In [83]:
def generate_2d_gaussian(kernel_size, sigma=1, mu=0):
    """
    Generates a 2D Gaussian array.

    Args:
        kernel_size (int): The size of the square Gaussian array (e.g., 5 for a 5x5 array).
        sigma (float): The standard deviation of the Gaussian distribution.
        mu (float): The mean of the Gaussian distribution (typically 0 for centering).

    Returns:
        numpy.ndarray: A 2D NumPy array representing the Gaussian.
    """
    # Create 1D arrays for x and y coordinates, centered around 0
    x = np.linspace(-(kernel_size // 2), kernel_size // 2, kernel_size)
    y = np.linspace(-(kernel_size // 2), kernel_size // 2, kernel_size)

    # Create 2D coordinate grids
    x_grid, y_grid = np.meshgrid(x, y)

    # Calculate the distance from the center
    distance_squared = x_grid**2 + y_grid**2

    # Apply the Gaussian function
    gaussian_array = np.exp(-(distance_squared / (2.0 * sigma**2)))

    # Normalize the array so its sum is 1 (optional, for kernels)
    gaussian_array /= np.sum(gaussian_array)

    return gaussian_array
kernel_size = 5
sigma_value = 1.0
generate_2d_gaussian(kernel_size, sigma=sigma_value)

array([[0.00296902, 0.01330621, 0.02193823, 0.01330621, 0.00296902],
       [0.01330621, 0.0596343 , 0.09832033, 0.0596343 , 0.01330621],
       [0.02193823, 0.09832033, 0.16210282, 0.09832033, 0.02193823],
       [0.01330621, 0.0596343 , 0.09832033, 0.0596343 , 0.01330621],
       [0.00296902, 0.01330621, 0.02193823, 0.01330621, 0.00296902]])

#### 57. How to randomly place p elements in a 2D array?

In [ ]:
a = np.arange(20).reshape(-1, 2)
idx = np.random.randint(0, len(a))
# a[idx] = 1000 # will not work because, not sure if use for row or column
# alternate solution would be flatten it, then put the index,
#  then shape it back, but that is not as elegant at np.put
np.put(a, idx, 1000)
a

array([[   0,    1],
       [   2,    3],
       [   4,    5],
       [1000,    7],
       [   8,    9],
       [  10,   11],
       [  12,   13],
       [  14,   15],
       [  16,   17],
       [  18,   19]])

#### 58. Subtract the mean of each row of a matrix

In [ ]:
a = np.arange(20).reshape(-1, 2)
a - a.mean(axis=1, keepdims=True)
# other way is longer and use np.expand_dims
# a - np.expand_dims(a.mean(axis=1), axis=1)

#### 59. How to sort an array by the nth column?

In [ ]:
# create a random matrix
a = np.random.uniform(0, 10, size=20).reshape((-1, 4))
# use np.argsort to sort the index for any column, then use that as the indices for the main matrix
column = 3 # get the fourth column, only that column should be sorted
a[np.argsort(a[:, column], axis=0)]

array([[3.7798759 , 7.05084364, 2.48724154, 3.30252529],
       [5.91888739, 3.50218247, 7.08181196, 4.81666988],
       [1.46604822, 5.13326169, 2.33228072, 5.81305417],
       [4.26091475, 2.22576418, 3.96651602, 8.91896909],
       [8.63138522, 8.80359969, 2.36685194, 9.07693706]])

#### 60. How to tell if a given 2D array has null columns?

#### 61. Find the nearest value from a given value in an array

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator?

#### 63. Create an array class that has a name attribute

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)?

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once?

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices?

#### 69. How to get the diagonal of a dot product?

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value?

#### 71. Consider an array of dimension (5,5,3), how to multiply it by an array with dimensions (5,5)?

#### 72. How to swap two rows of an array?

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles 

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C?

#### 75. How to compute averages using a sliding window over an array?

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1])


#### 77. How to negate a boolean, or to change the sign of a float inplace?

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])?

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])?


#### 80. Consider an arbitrary array, write a function that extracts a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary)


#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?


#### 82. Compute a matrix rank

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i]

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1))

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)?

#### 88. How to implement the Game of Life using numpy arrays?

#### 89. How to get the n largest values of an array

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combination of every item)

#### 91. How to create a record array from a regular array?

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B?

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3])

#### 95. Convert a vector of ints into a matrix binary representation 

#### 96. Given a two dimensional array, how to extract unique rows?

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. 


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means).


